import process from 'node:process';
import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { deriveTraceFixture, createSourceSystemProfileTile, createSourceRecordTile, createSourceManifestationTile, createSourceEpisodeTile } from '../../packages/source-substrate/dist/index.js';
import { canonicalizeJson } from '../../packages/rosetta-canon/dist/index.js';
const hash = bytes => createHash('sha256').update(bytes).digest('hex');
const root = process.cwd();
const privatePath = path.resolve(process.argv[2] ?? '');
const receiptPath = path.resolve(process.argv[3] ?? '');
if (!process.argv[2] || !process.argv[3] || privatePath.startsWith(root + path.sep) || receiptPath.startsWith(root + path.sep)) throw new Error('Private input and receipt must stay outside the checkout.');
const raw = readFileSync(privatePath, 'utf8');
const result = deriveTraceFixture(raw, { start: 0, count: 75 });
if (canonicalizeJson(result) !== canonicalizeJson(deriveTraceFixture(raw, { start: 0, count: 75 }))) throw new Error('Nondeterministic derivation.');
if (/Bearer\s|eyJ[A-Za-z0-9_-]+\.|https?:\/\/|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/i.test(result.fixture)) throw new Error('Fixture disclosure scan failed.');
const publicPath = 'packages/source-substrate/test-vectors/trace/captured-derived.sse';
const profile = createSourceSystemProfileTile({ sourceSystemId: 'chatgpt-stream-export', canonicalName: 'ChatGPT stream export', sourceRoles: ['source-evidence'], capabilityFacets: ['captured-stream'], curationPosture: 'bounded-fixture', reviewPosture: 'disclosure-allowlist', preservationPosture: 'private-original-retained', rightsPosture: 'split', evidenceRefs: ['private-capture-001'] });
const record = createSourceRecordTile({ sourceSystemId: 'chatgpt-stream-export', recordLocalId: 'capture-001', stableLocators: ['private-capture-001'], recordType: 'agent-client-sse-stream', publicationStatus: 'private-original-public-derivative', metadataBlob: { family: 'chat-transcript' } }, [profile.cid]);
const original = createSourceManifestationTile({ sourceRecordCid: record.cid, manifestationId: 'original-001', manifestationKind: 'captured-stream-log', mediaType: 'text/event-stream', byteHashes: {}, accessRequirements: ['local-private', 'no-external-publish'], structureProfile: 'chatgpt-sse-stream/private-v1' }, [record.cid]);
const derived = createSourceManifestationTile({ sourceRecordCid: record.cid, manifestationId: 'derived-001', manifestationKind: 'redacted-structural-fixture', mediaType: 'text/event-stream', byteHashes: { sha256: hash(result.fixture) }, accessRequirements: ['public-structural-fixture'], structureProfile: result.manifest.profile }, [record.cid, original.cid]);
const episode = createSourceEpisodeTile({ episodeId: 'trace-source-001', family: 'chat-transcript', locator: publicPath, rawEvidenceRefs: [{ evidenceId: 'derived-001', evidenceKind: 'local-file', locator: publicPath, sha256: hash(result.fixture) }], rightsScope: ['public-structural-fixture'], chronology: { primary: { date: '2000-01-01', kind: 'relative-redacted', source: 'trace-src-redaction-v1' } }, mode: 'parse-only', classification: { confidence: 1, reasons: ['fixture transport declaration'] }, sourceRecordCid: record.cid, sourceManifestationCid: derived.cid }, [derived.cid]);
writeFileSync(publicPath, result.fixture);
writeFileSync('packages/source-substrate/test-vectors/trace/redaction-manifest.json', canonicalizeJson(result.manifest) + '\n');
writeFileSync('packages/source-substrate/test-vectors/trace/source-bundle.json', canonicalizeJson({ profile, record, original, derived, episode }) + '\n');
writeFileSync(receiptPath, JSON.stringify({ originalSha256: hash(raw), derivedSha256: hash(result.fixture), originalManifestationCid: original.cid, derivedManifestationCid: derived.cid, window: result.manifest.window, privateEvidenceId: 'private-capture-001' }, null, 2) + '\n', { mode: 0o600 });
process.stdout.write('75 captured-derived events; deterministic replay and public secret scan passed.\n');
